"""initial

Revision ID: cbb6d3afeda1
Revises: 
Create Date: 2026-03-08 16:07:35.283374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbb6d3afeda1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=False),
    sa.Column('positions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_players_name')
    )
    op.create_table('team_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team', sa.String(length=5), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team', 'week_num', name='uq_team_schedule_team_week')
    )
    op.create_table('player_projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('pts_pg', sa.Float(), nullable=False),
    sa.Column('reb_pg', sa.Float(), nullable=False),
    sa.Column('ast_pg', sa.Float(), nullable=False),
    sa.Column('stl_pg', sa.Float(), nullable=False),
    sa.Column('blk_pg', sa.Float(), nullable=False),
    sa.Column('tov_pg', sa.Float(), nullable=False),
    sa.Column('tpm_pg', sa.Float(), nullable=False),
    sa.Column('fg_pct', sa.Float(), nullable=False),
    sa.Column('ft_pct', sa.Float(), nullable=False),
    sa.Column('fantasy_ppg', sa.Float(), nullable=False),
    sa.Column('projected_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'week_num', name='uq_projection_player_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_projections')
    op.drop_table('team_schedules')
    op.drop_table('players')
    # ### end Alembic commands ###
