/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/compare` | `/compare`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lineup` | `/lineup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/player-grid` | `/player-grid`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projections` | `/projections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roster` | `/roster`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/compare` | `/compare`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lineup` | `/lineup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/player-grid` | `/player-grid`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projections` | `/projections`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/roster` | `/roster`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/compare${`?${string}` | `#${string}` | ''}` | `/compare${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lineup${`?${string}` | `#${string}` | ''}` | `/lineup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/player-grid${`?${string}` | `#${string}` | ''}` | `/player-grid${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projections${`?${string}` | `#${string}` | ''}` | `/projections${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/roster${`?${string}` | `#${string}` | ''}` | `/roster${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/teams${`?${string}` | `#${string}` | ''}` | `/teams${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/compare` | `/compare`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lineup` | `/lineup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/player-grid` | `/player-grid`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projections` | `/projections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roster` | `/roster`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownInputParams; };
    }
  }
}
